### ISSUE TITLE
The Gate definition 'viewWebLogs' is overridden.

### ISSUE THREAD

**Issue by Oxicode** [mojtabaahn/laravel-web-logs#11]
![image](https://user-images.githubusercontent.com/1320709/128468646-1662cfec-6f7f-42f3-9f61-0af4993f4ccf.png)

**Comment by mojtabaahn** [comment]
Hello Christian and thanks for report.
I believe you're using [laravel-microscope](https://github.com/imanghafoori1/laravel-microscope) for checking any probable bugs.
Overriding gates should not be a bug as long as we know which definition is being called when and where and I believe it should not result errors in the process.
One possible way to handle this is having a config option to suppress such errors in utilized library.
The other one would be changing our end, checking if the gate already exists using [Gate::has](https://laravel.com/api/5.8/Illuminate/Auth/Access/Gate.html#method_has) and defining it only if it's missing.
Let me know if you have a better approach solving it.
