### ISSUE TITLE
Remove hardcoded Gate::define()

### ISSUE THREAD

**Issue by dannydinges** [mojtabaahn/laravel-web-logs#3]
Can we have the hardcoded Gate::define() removed from the package Service Provider and instead allow the user to define the gate within their AuthServiceProvider? Allows for more flexibility for limiting access to the interface.

**Comment by mojtabaahn** [comment]
The hard-coded `Gate::define()` in `LaravelWebLogsServiceProvider` class is a fallback gate and is used in case no gate with same name is already defined.

Considering that you can define same gate in your `AuthServiceProvider` class and it will overwrite default gate.

```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Gate::define('viewWebLogs', function ($user) {
            return $user->is_admin;
        });
    }
}
```

**Comment by mojtabaahn** [comment]
Also an [Authorization](https://github.com/mojtabaahn/laravel-web-logs#authorization) section just added to README that points to the same problem.

**Comment by dannydinges** [comment]
Great thanks for the help. I think the missing piece for me is you need to be able to assign the "web" middleware to the route or you can't get the $user in the Gate. Might be a good config option to define middleware to add to the routes.

**Comment by mojtabaahn** [comment]
Oh, that's actually true. I'm using lumen for tests and didn't see that happen..
I think we're gonna add a configuration option to specify web-logs route group attributes including middleware.
Thanks for feedback

**Comment by mojtabaahn** [comment]
in version ^1.1 a new config have been added `route_group_attributes` and it is possible customize middleware. so it is possible to enable web middleware by uncommenting it in middleware option:

```php
use Mojtabaahn\LaravelWebLogs\Http\Middlewares\Authorize;

return [
    // ...

    /*
    |--------------------------------------------------------------------------
    | Route Group Attributes
    |--------------------------------------------------------------------------
    |
    | This is the array configuring package route attributes. feel free
    | to edit route prefixes, middlewares and anything else.
    |
    | In case you want to add authorization using default auth driver (session
    | driver), uncomment web middleware.
    |
    */

    'route_group_attributes' => [
        'prefix' => 'web-logs',
        'middleware' => [
            // 'web',
            Authorize::class,
        ],
    ],

    // ...
];
```

**Comment by dannydinges** [comment]
@mojtabaahn Thanks for the quick fix/addition. Appreciate it!
