### ISSUE TITLE
Clear logs

### ISSUE THREAD

**Issue by jhemmmm** [mojtabaahn/laravel-web-logs#5]
Hello,

How do we clear the logs?.

**Comment by mojtabaahn** [comment]
Hi, currently there is no delete option but would implement it if we find it useful.
Can you clarify what do you mean by clearing logs? to completely remove a log file? removing a single log report in a log file?
And what are use cases?

**Comment by jhemmmm** [comment]
> Hi, currently there is no delete option but would implement it if we find it useful.
> Can you clarify what do you mean by clearing logs? to completely remove a log file? removing a single log report in a log file?
> And what are use cases?

Clear the whole logs. I usually clear my logs if there's any errors that have been already fixed.

**Comment by AhmadWaleed** [comment]
@jhemmmm This package provide very simple log explorer to view and monitor your application log files, for your case you should look into error reporting / monitoring tool like sentry as mentioned in the readme of this package.

**Comment by mojtabaahn** [comment]
Thanks for sharing your thoughts @jhemmmm @AhmadWaleed.

I'm not gonna implement this currently since I don't see use-case for myself.

but I'm open to PRs.
