### ISSUE TITLE
Assets not loading on production

### ISSUE THREAD

**Issue by adddz** [mojtabaahn/laravel-web-logs#8]
Hi there, great package!

It works very well on development but I'm having issues with it on a production environment.

When I visit `site.com/web-logs`, I see a blank page with these errors:

<img width="1914" alt="Screenshot 2021-05-31 at 22 47 31" src="https://user-images.githubusercontent.com/28903217/120241129-67dc3380-c262-11eb-924f-676dc2775a92.png">

The interesting thing is that if I open these assets files in a new tab, they load correctly.
For some reasons they are not loaded from the main route `/web-logs`.

Any ideas?

**Comment by mojtabaahn** [comment]
Hello and thanks.

This is weird, Can you share more details, what version are you using, did you change default configs, and what are generated asset links?

**Comment by adddz** [comment]
Hey there.

Version: 1.2.2
I didn't change the configs and the generated asset links are these:

```
<script>
    window.backend_base_url = 'https://example.org/web-logs'
</script>
<script defer="defer" src="https://example.org/web-logs/assets/js/chunk-vendors.js" type="module"></script>
<script defer="defer" src="https://example.org/web-logs/assets/js/app.js" type="module"></script>
<link href="https://example.org/web-logs/assets/css/chunk-vendors.css" rel="stylesheet">
<link href="https://example.org/web-logs/assets/css/app.css" rel="stylesheet">
<script defer="defer" src="https://example.org/web-logs/assets/js/chunk-vendors-legacy.js" nomodule></script>
<script defer="defer" src="https://example.org/web-logs/assets/js/app-legacy.js" nomodule></script>
```

**Comment by mojtabaahn** [comment]
Well, Assuming you are brwosing over https (so no CORS error happen) It all seems OK.

The only tricky thing here that might be related to this, is that assets are being served by a route (web-logs/assets/{asset}). but the fact that they are being served normally when you open them in a new tab would assure it is working well ( right ? )

**Comment by adddz** [comment]
Exactly, they’re being loaded just fine in a new tab. May I ask why are the assets served by a route?

Maybe if there would be a command to publish the assets just like for most other Laravel packages, that would be more compatible in different environments?

**Comment by mojtabaahn** [comment]
Well it used to be publishable in v1.0.*, the problem with that approach is that you need to re-publish those assets every time we make an update in front-end. I personally find that annoying specially when package is unstable and there will be updates frequently. and also I see no benefits in making bundled assets publishable, I mean their not customizable, so what's the point of making them publishable?

For your specific problem I suggest trying to downgrade to 1.0.* and check if it is related to dynamic assets or not?

**Comment by jpmurray** [comment]
I had this problem locally, and it occured because I changed the access URL from `web-logs` to `admin/web-logs`. Assets where still trying to be accessed from `web-logs` path. Reverting to default URL makes it work fine.

**Comment by mojtabaahn** [comment]
@jpmurray thanks for feedback. Changing package URL **will not change asset URLs** and it is intended. but it should not break the app. have you tried updating to latest version?

**Comment by jpmurray** [comment]
@mojtabaahn I'm on 1.3.2. As soon as I change the URL, `chunk-vendor.js`, `app.js`, `chunk-vendor.css` and `app.css` gets 404'd.

**Comment by mojtabaahn** [comment]
@jpmurray whoops! that's what happen when I don't add tests and hope for the best :facepalm:. Pushed 1.3.3 to fix that. sorry for inconvenience and thanks for feedback again.

**Comment by jpmurray** [comment]
Working 💯 on `1.3.3`! 👍
